# Generated by Django 4.2.7 on 2023-11-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('classId', models.IntegerField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=10)),
                ('activeFrom', models.DateField()),
                ('activeTo', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'db_table': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('typeId', models.IntegerField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Grade Types',
                'db_table': 'Grade Types',
            },
        ),
        migrations.CreateModel(
            name='GradeValue',
            fields=[
                ('gradeId', models.FloatField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Grade Values',
                'db_table': 'Grade Values',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleId', models.IntegerField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='SubjectTypes',
            fields=[
                ('typeId', models.IntegerField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Subject types',
                'db_table': 'Subject types',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradjaApp.roles')),
                ('studentParent', models.ManyToManyField(related_name='StudentParent', to='GradjaApp.users')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subjectId', models.IntegerField(primary_key=True, serialize=False)),
                ('activeFrom', models.DateField()),
                ('activeTo', models.DateField()),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradjaApp.classes')),
                ('subjectType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradjaApp.subjecttypes')),
                ('teacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradjaApp.users')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'db_table': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('mailId', models.IntegerField(primary_key=True, serialize=False)),
                ('sendDate', models.DateField()),
                ('topic', models.CharField(max_length=200)),
                ('mailText', models.TextField()),
                ('fromId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromId', to='GradjaApp.users')),
                ('toId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toId', to='GradjaApp.users')),
            ],
            options={
                'verbose_name_plural': 'Mails',
                'db_table': 'Mails',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradjaApp.subjects')),
                ('gradeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradjaApp.gradevalue')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradjaApp.users')),
                ('typeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradjaApp.gradetype')),
            ],
            options={
                'verbose_name_plural': 'Grades',
                'db_table': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='ClassStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeFrom', models.DateField()),
                ('activeTo', models.DateField()),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradjaApp.classes')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentId', to='GradjaApp.users')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='classStudent',
            field=models.ManyToManyField(through='GradjaApp.ClassStudents', to='GradjaApp.users'),
        ),
        migrations.AddField(
            model_name='classes',
            name='homeroomTeacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroomTeacher', to='GradjaApp.users'),
        ),
    ]
