# Generated by Django 4.2.7 on 2023-11-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GradjaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classstudents',
            options={'verbose_name_plural': 'Class Students'},
        ),
        migrations.AlterModelTable(
            name='classstudents',
            table='Class Students',
        ),
    ]
