# Generated by Django 4.2.7 on 2023-12-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GradjaApp', '0002_alter_users_name_alter_users_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.RemoveField(
            model_name='users',
            name='surname',
        ),
    ]
