# Generated by Django 4.2.8 on 2023-12-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GradjaApp', '0003_remove_users_name_remove_users_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='id',
        ),
        migrations.AddField(
            model_name='grades',
            name='gradeValueId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GradjaApp.gradevalue'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='gradeId',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
