# Generated by Django 4.2.8 on 2023-12-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradjaApp', '0004_remove_grades_id_grades_gradevalueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='gradeId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
