# Generated by Django 4.2.8 on 2023-12-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradjaApp', '0006_alter_grades_gradeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='gradeId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
